apiVersion: v1
kind: Service
metadata:
  name: flutter-front-service
  labels:
    app: flutter-front
spec:
  selector:
   app: flutter-front
  type: NodePort 
  ports:
   - port: 80
     nodePort: 30100